gestionBanquierFront/gestionBanquierFront/Controllers/CreditController.cs
using gestionBanquierFront.Models;
using gestionBanquierFront.Utils;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace gestionBanquierFront.Controllers
{
    public class CreditController : Controller
    {

        HttpClient httpClient;
        public CreditController()
        {
            httpClient = HttpClientAccessor.HttpClient;


        }

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", (string)Session["accessToken"]);
        }

        // GET: Credit
        public ActionResult Index()
        {

            var creditList = httpClient.GetAsync("credits/list").Result;

            if (creditList.IsSuccessStatusCode)
            {
                var response = creditList.Content.ReadAsAsync<List<Credit>>().Result;
                return View(response);
            }

            return View();
        }

        // GET: Credit/Details/1
        public ActionResult Details(int id)
        {
            var creditList = httpClient.GetAsync("credits/" + id).Result;

            if (creditList.IsSuccessStatusCode)
            {
                var response = creditList.Content.ReadAsAsync<Credit>().Result;
                return View(response);
            }
            return View();
        }

        // GET: Credit/Create
        public ActionResult Create()
        {
            return View();
        }


        private ActionResult RedirectToIndex(string v)
        {
            throw new NotImplementedException();
        }

        // POST: Credit/Create
        [HttpPost]
        public async Task<ActionResult> Create(Credit credit)
        {

            try
            {
                var response = await httpClient.PostAsJsonAsync("credits/new", credit);

                if (response.IsSuccessStatusCode)
                {
                    var result = response.Content.ReadAsStringAsync();
                    return RedirectToAction("Index");
                }
                else
                {
                    response.EnsureSuccessStatusCode();
                    return View();
                }

            }
            catch
            {
                return View();
            }
        }

        // GET: Credit/Edit/5
        public ActionResult Edit(int id)
        {

            var creditList = httpClient.GetAsync("credits/" + id).Result;

            if (creditList.IsSuccessStatusCode)
            {
                var response = creditList.Content.ReadAsAsync<Credit>().Result;
                return View(response);
            }
            return View();
        }

        // POST: Credit/Edit/5
        [HttpPost]
        public ActionResult EditAsync(Credit credit)
        {
            try
            {

                {
                    var response = httpClient.PostAsJsonAsync("credits/update", credit);

                }

                /* var creditList = httpClient.PostAsync("credits/update", credit).Result;

                 if (creditList.IsSuccessStatusCode)
                 {
                     var response = creditList.Content.ReadAsAsync<Credit>().Result;
                     return View(response);
                 }*/
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Credit/Delete/5
        public ActionResult Delete(int id)
        {
            var creditList = httpClient.GetAsync("credits/" + id).Result;

            if (creditList.IsSuccessStatusCode)
            {
                var response = creditList.Content.ReadAsAsync<Credit>().Result;
                return View(response);
            }
            return View();
        }
        // POST: Credit/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {


            var creditList = httpClient.DeleteAsync("credits/" + id + "/delete").Result;

            if (creditList.IsSuccessStatusCode)
            {
                var response = creditList.Content.ReadAsAsync<List<Credit>>().Result;
                return View(response);
            }


            return RedirectToAction("Index");


        }

        // POST: Credit/CalculScore/5
        [HttpPost]
        public ActionResult CaldulScore(int id)
        {


            var creditList = httpClient.DeleteAsync("credits/" + id + "/score").Result;

            if (creditList.IsSuccessStatusCode)
            {
                var response = creditList.Content.ReadAsAsync<List<Credit>>().Result;
                return View(response);
            }


            return RedirectToAction("Index");


        }

    }
}

gestionBanquierFront/gestionBanquierFront/Controllers/UserController.cs
using gestionBanquierFront.Models;
using gestionBanquierFront.Utils;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace gestionBanquierFront.Controllers
{
    public class UserController : Controller
    {

        HttpClient httpClient;

        public UserController()
        {
            httpClient = HttpClientAccessor.HttpClient;
            //httpClient.BaseAddress = new Uri("http://localhost:8082/api/auth/");
            // httpClient.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            //httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", (string)Session["accessToken"]);

            ViewBag.userList = new SelectList(new List<SelectListItem>());
        }

        protected override void Initialize(RequestContext requestContext)
        {
            base.Initialize(requestContext);
            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", (string)Session["accessToken"]);
        }

        // GET: User
        public ActionResult Index()
        {


            var userListResponse = httpClient.GetAsync("auth/users").Result;

            if (userListResponse.IsSuccessStatusCode)
            {
                var response = userListResponse.Content.ReadAsAsync<List<User>>().Result;
                return View(response);
            }

            return View();
        }

        // GET: User/PDF/5

        public ActionResult ExportPDF()
        {
            var user = httpClient.GetAsync("auth/users/export/pdf").Result;
               
                var response = user.Content.ReadAsStringAsync().Result;
            return File(response, "application/pdf", "report.pdf");
            

            
        }
        public ActionResult ExportCSV()
        {
            var user = httpClient.GetAsync("auth/users/export/csv").Result;
            
                var response = user.Content.ReadAsStringAsync().Result;
                //string csv = ListToCSV(response);

                return File(new System.Text.UTF8Encoding().GetBytes(response), "text/csv", "report.csv");
            
        }


        // GET: Account/Create
        public ActionResult Create()
        {
            ViewBag.userList = new SelectList(Enumerable.Empty<User>());
            var userList = httpClient.GetAsync("auth/users").Result;
            if (userList.IsSuccessStatusCode)
            {
                var response = userList.Content.ReadAsAsync<List<User>>().Result;
                var itemsList = new List<SelectListItem>();
                response.ForEach(x =>
                {
                    itemsList.Add(new SelectListItem
                    {
                        Text = x.nom + " " + x.prenom,
                        Value = x.id.ToString()
                    });
                });
                ViewBag.userList = itemsList;
            }
            return View();
        }
        // POST: Account/Create
        [HttpPost]
        public async Task<ActionResult> Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                var provider = CultureInfo.InvariantCulture;
                var user = new CreateUserModel
                {

                    nom = collection["nom"],
                    prenom = collection["prenom"],

                    email = collection["email"],

                    username = collection["username"],

                    password = collection["password"],

                };



                //string jsonString = JsonConvert.SerializeObject(account);

                var response = await httpClient.PostAsJsonAsync("auth/register/", user);

                if (response.IsSuccessStatusCode)

                {
                    
                    var result = response.Content.ReadAsStringAsync();
                    return RedirectToAction("Index");
                }
                else
                {
                    response.EnsureSuccessStatusCode();
                    return View();
                }

            }
            catch (Exception e)
            {
                return View();
                Console.WriteLine(e.Message);
                Console.WriteLine(e.StackTrace);
                return View("Index");
            }
        }


        // GET: Account/Edit/5
        public ActionResult Edit(int id)
        {


            var user = httpClient.GetAsync("auth/users/" + id).Result;

            if (user.IsSuccessStatusCode)

            {
                var result = user.Content.ReadAsStringAsync().Result;
                var processedObject = JsonConvert.DeserializeObject<User>(result);
                return View(processedObject);
            }
            else
            {
                user.EnsureSuccessStatusCode();
                return View();
            }
        }

        // POST: Account/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(int id, FormCollection collection)
        {
            try
            {
                var user = new EditUserModel
                {

                    nom = collection["nom"],
                    prenom = collection["prenom"],
                    email = collection["email"],
                    username = collection["username"],


                };
                user.id = id;

                var response = await httpClient.PostAsJsonAsync("auth/updateusers/" + id, user);

                if (response.IsSuccessStatusCode)

                {
                    var result = response.Content.ReadAsStringAsync();
                    return RedirectToAction("Index");
                }
                else
                {
                    response.EnsureSuccessStatusCode();
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        
        
        // GET: Uerr/Details/5
        public ActionResult Details(int id)
        {

            var user = httpClient.GetAsync("auth/getuser/" + id).Result;

            if (user.IsSuccessStatusCode)

            {
                var result = user.Content.ReadAsStringAsync().Result;
                var processedObject = JsonConvert.DeserializeObject<User>(result);
                return View(processedObject);
            }
            else
            {
                user.EnsureSuccessStatusCode();
                return View();
            }
        }



        // POST: Account/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            try
            {

                var response = await httpClient.PostAsync("auth/deleteusers/" + id, null);

                if (response.IsSuccessStatusCode)

                {
                    var result = response.Content.ReadAsStringAsync();
                    return RedirectToAction("Index");
                }
                else
                {
                    response.EnsureSuccessStatusCode();
                    return View();
                }


            }
            catch
            {
                return View();
            }
        }
    }
}

gestionBanquierFront/gestionBanquierFront/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>DigiBank</title>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>

    @Styles.Render("~/Content/styles.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Content/js/scripts.js")
    @Scripts.Render("~/Content/js/bootstrap.bundle.js")
    @Scripts.Render("~/Content/js/bootstrap.bundle.min.js")
</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="#">Digibank</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group" hidden>
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                 
                    <li><a class="dropdown-item" href="@Url.Action("Logout", "Account")">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="index.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Interface</div>
                        @if (Session["username"] != null)
                        {
                            if (Session["role"].Equals("ADMINISTRATEUR"))
                            {
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                    Account
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="@Url.Action("Create", "Account")">Add Account</a>
                                        <a class="nav-link" href="@Url.Action("Index", "Account")">List Account</a>
                                        <a class="nav-link" href="#">Show stats</a>
                                    </nav>
                                </div>

                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayoutsUsers" aria-expanded="false" aria-controls="collapseLayouts">
                                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                    Users
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="collapseLayoutsUsers" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="@Url.Action("Create", "User")">Add User</a>
                                        <a class="nav-link" href="@Url.Action("Index", "User")">List Users</a>
                                        <a class="nav-link" href="#">Show stats</a>
                                    </nav>
                                </div>

                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayoutsCredit" aria-expanded="false" aria-controls="collapseLayouts">
                                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                    Credit
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="collapseLayoutsCredit" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="@Url.Action("Create", "Credit")">Add Credit</a>
                                        <a class="nav-link" href="@Url.Action("Index", "Credit")">List Credit</a>
                                    </nav>
                                </div>

                            }
                        }
                        @*<a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
            Pages
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>*@ @* <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">*@ @* <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">*@ @*<a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
        Authentication
        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
    </a>
    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
        <nav class="sb-sidenav-menu-nested nav">
            <a class="nav-link" href="login.html">Login</a>
            <a class="nav-link" href="register.html">Register</a>
            <a class="nav-link" href="password.html">Forgot Password</a>
        </nav>
    </div>*@ @*<a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
        Error
        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
    </a>
    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
        <nav class="sb-sidenav-menu-nested nav">
            <a class="nav-link" href="401.html">401 Page</a>
            <a class="nav-link" href="404.html">404 Page</a>
            <a class="nav-link" href="500.html">500 Page</a>
        </nav>
    </div>*@ @*  </nav>*@ @*   </div>*@ @*<div class="sb-sidenav-menu-heading">Addons</div>
    <a class="nav-link" href="charts.html">
        <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
        Charts
    </a>
    <a class="nav-link" href="tables.html">
        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
        Tables
    </a>*@
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                  
                    @if (Session["username"] != null)
                    {
                       @Session["username"];
                    }
                </div>
            </nav>
        </div>
        @RenderBody()
    </div>


</body>
</html>

gestionBanquierFront/gestionBanquierFront/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Login - SB Admin</title>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    @Styles.Render("~/Content/styles.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Content/js/scripts.js")
</head>
<body class="bg-primary">

    @RenderBody()
    <div id="layoutAuthentication_footer">
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; DigiBank 2021</div>
                    <div>
                        <a href="#">Privacy Policy</a>
                        &middot;
                        <a href="#">Terms &amp; Conditions</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    
   
</body>
</html>